### ISSUE TITLE
VegaLite axis titles disappear when pushing data

### ISSUE THREAD

**Issue by mcintyre94** [elixir-nx/kino#27] opened 2021-06-26 14:58 UTC
I'm rendering a VegaLite graph with axis titles:

```elixir
widget =
  Vl.new(width: 600, height: 400)
  |> Vl.mark(:line, point: true)
  |> Vl.encode_field(:x, "iteration", type: :quantitative, title: "Iteration")
  |> Vl.encode_field(:y, "time", type: :quantitative, title: "Time (ms)")
  |> Kino.VegaLite.new()
```

I'm then pushing data to it, in the same way as the demo LiveBook does:

```elixir
for i <- 1..iterations do
  {usecs, :ok} = :timer.tc(make_request)
  millisecs = usecs/1000
  Kino.VegaLite.push(widget, %{iteration: i, time: millisecs})
end
```

This works, but the graph seems to lose the axis titles as soon as data is pushed - the x axis title disappears completely, and the y axis title is split vertically making it illegible.

See short video demonstrating this:

https://user-images.githubusercontent.com/1711350/123517087-2db25600-d697-11eb-96e9-f9d713e34a5c.mov

I installed using:

```elixir
Mix.install([
  {:kino, "~> 0.2.0"},
  {:vega_lite, "~> 0.1.0"},
  ...
])
```

**Comment by jonatanklosko** [comment] 2021-06-26 15:55
Good catch! The problem is on Livebook side, the graphic layout changes as we stream data to the client, but the axes are not automatically adjusted on every change. Should be addressed by https://github.com/elixir-nx/livebook/pull/405 :)

**Closed** 2021-06-26 16:05 UTC

**Comment by mcintyre94** [comment] 2021-06-26 16:21
That fix works great, thanks so much! :)

**Comment by jonatanklosko** [comment] 2021-06-26 16:22
@mcintyre94 Perfect, thanks for checking! :shipit:
